#
# Test unroll-and-jam. The last loop adapted from the simple
# convolution example from p463 of "Optimizing Compilers for
# Modern Architectures", by Randy Allen and Ken Kennedy.
#

source: unroll.c
procedure: foo
format: rose
# fully unroll a loop with known iteration count
loop: 0
original()
unroll(0,1,3)
print
print space


# a strided loop
loop: 1
original()
unroll(0,1,2)
print
print space

# lower and upper bounds are not constant
loop: 2
original()
unroll(0,1,20)
print

# parallelogram iteration space
loop: 3
original()
unroll(0,1,2)
print
