# Edit this file to customize for your system.

# whether CodeGen+ is built
BUILD_CODEGEN = true

ifneq ($(strip $(wildcard $(ROSEHOME))),)
BUILD_ROSE = true
BUILD_SUIF = false
else
BUILD_ROSE = false
endif

CC = g++
# CC = icc -Kc++ 
CFLAGS = -g
DEPENDENCE_CFLAGS = -M

AR = ar

INCL_PATH = -I$(BASEDIR)/basic/include -I../include
LIBS = 
LIB_PATH = 

# default installation path
ifeq ($(shell whoami), root)
DEST_DIR = /usr/local/
else
DEST_DIR = $(HOME)/
endif
# uncomment below to overwrite default path
# DEST_DIR =

# DO NOT CHANGE
OMEGA_BUILD_DATE = $(shell date +%m/%d/%Y)

