# Basic illustration of loop fusion and distribution.

source: fuse_distribute.sp2
format: suif
procedure: 0
loop: 0-0 # just show syntax of initializing multiple loops together

# initially fused as much as possible
original()
print

# distribute the first two statements
distribute([0,1], 2)
print

# prepare the third statement for fusion
shift([2], 2, 1)
print

# fuse the last two statements
fuse([1,2],2)
print
