stages:
    - build
    - test

build-cmake-rose:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake .. -DFRONTEND=Rose
        - make $CMAKEBUILD
    only:
        - master
        - /^cmake-.*$/
    artifacts:
        paths:
            - build/
        expire_in: 1 day

build-cmake-clang:
    stage: build
    script:
        - mkdir build
        - cd build
        - cmake .. -DFRONTEND=Clang
        - make $CMAKEBUILD
    only:
        - master
        - /^cmake-.*$/
    artifacts:
        paths:
            - build/
        expire_in: 1 day

build-automake:
    stage: build
    script:
        - ./bootstrap
        - ./configure --disable-debug
        - make
    only:
        - master
    artifacts:
        untracked: true
        expire_in: 1 day

test-cmake-rose:
    stage: test
    dependencies:
        - build-cmake-rose
    script:
        - cd build
        - make check-all
    only:
        - master
        - /^cmake-.*$/
    artifacts:
        untracked: true
        expire_in: 1 week
        when: on_failure

test-cmake-clang:
    stage: test
    dependencies:
        - build-cmake-clang
    script:
        - cd build
        - make check-all
    only:
        - master
        - /^cmake-.*$/
    artifacts:
        untracked: true
        expire_in: 1 week
        when: on_failure
    # fail in this job doesn't make the whole CI fail
    allow_failure: true


test-automake:
    stage: test
    dependencies:
        - build-automake
    script:
        - make
        - make check
    only:
        - master
    artifacts:
        untracked: true
        expire_in: 1 week
        when: on_failure

