#!/bin/bash

root_src_dir="$(dirname $0)"
pushd $root_src_dir >/dev/null

./test-chill/make_chill_testcases.sh examples/chill/testcases examples/chill/testcases/RIGHTANSWERS

##TODO: add cuda-chill tests
echo "" > ./test-chill/cudachill_testcases.mk

autoreconf -if

popd >/dev/null

