#!/bin/bash

is_test_file() {
    if [ -n `sed -n "s/^destination(.*)/\0/p" $1` ]; then
        echo 1;
    else
        echo 0;
    fi
}

make_test_file="test-chill/chill_testcases.mk"
echo "## autogenerated from test-chill/make_chill_testcases.sh $@" > $make_test_file


for test_dir in $@;
do
    for test_file_path in `ls $test_dir/*.py`
    do
        if [ `is_test_file $test_file_path` -ne 0 ]; then
            test_file=`basename $test_file_path`
            
            ## Add run test
            run_test_file="test-chill/test-$test_file.test"
            
            echo "#!/bin/bash"                                                                                      >  $run_test_file # make new file
            echo "err=\`\$SRCDIR/test-chill/runchilltest.sh ./chill \$SRCDIR/$test_dir/$test_file check-run\`"    >> $run_test_file
            echo "exit \$?"                                                                                         >> $run_test_file
            chmod +x $run_test_file
            
            
            echo "TESTS += $run_test_file"                                                                          >> $make_test_file
        fi
    done
done
