source:jacobi_box_4_64.c
procedure:smooth_box_4_64
format: rose
loop:0


original()
print


skew([0,1,2,3,4,5],2,[2,1])
print

permute([2,1,3,4])
print


distribute([0,1,2,3,4,5],2)
print


stencil_temp(0)
#print
#print space

#stencil_ASE_padded(5)
#print
#print space

#fuse([2,3,4,5,6,7,8,9],1)
#print
#fuse([2,3,4,5,6,7,8,9],2)
#print
#fuse([2,3,4,5,6,7,8,9],3)
#print
#fuse([2,3,4,5,6,7,8,9],4)
#print

