#!/bin/sh

## input:
#   $1 - harness file path

get_opt_from_c() {
    ## input
    #   $1 - file path
    #   $2 - option name
    
    eval local pattern="'^\/\/>$2:\s*'"
    echo `sed -n s/$pattern//p $1`
}

chill_dir=`readlink -f $(dirname $0)/../../`
harness_dir=`readlink -f $(dirname $1)`
harness_name=`basename $1`
test_dir=$chill_dir/test-chill/

harness_source=$harness_dir/$harness_name
procedure_name=`get_opt_from_c $1 procedure_name`
procedure_compiler=`get_opt_from_c $1 procedure_compiler`
procedure_linker=`get_opt_from_c $1 procedure_linker`
original_header=$chill_dir/`get_opt_from_c $1 original_header`
original_source=$chill_dir/`get_opt_from_c $1 original_source`
generated_source=$chill_dir/`get_opt_from_c $1 generated_source`

harness_object="./harness_object.o"
procedure_source="./procedure_generated.${generated_source##*.}"
procedure_object="./procedure_object.o"
test_exec="./test_exec"

echo "#!/bin/sh"
echo "## generated by $0"
echo ""
echo "#harness_source             = \"$harness_source\""
echo "#procedure_name             = \"$procedure_name\""
echo "#procedure_compiler         = \"$procedure_compiler\""
echo "#procedure_linker           = \"$procedure_linker\""
echo "#original_header            = \"$original_header\""
echo "#original_source            = \"$original_source\""
echo "#generated_source           = \"$generated_source\""
echo "#combinded_procedure_source = \"$procedure_source\""
echo ""
echo ""
echo "## step into the test directory"
echo "#pushd $test_dir > /dev/null"
echo ""
echo "## compile harness"
echo "g++ -std=c++11 -c $harness_source -o $harness_object"
echo ""
echo "## create & compile procedure source"
echo "m4 \\"
echo "      -Dproc_name=$procedure_name\\"
echo "      -Doriginal_header=$original_header\\"
echo "      -Doriginal_source=$original_source\\"
echo "      -Dgenerated_source=$generated_source\\"
echo "      $harness_dir/c-wrapper.c.m4 > $procedure_source"
echo ""
echo "$procedure_compiler -c $procedure_source -o $procedure_object"
echo ""
echo "## link"
echo "$procedure_linker $harness_object $procedure_object -o $test_exec"
echo ""
echo "## run test"
echo "$test_exec"
echo "err_code=\$?"
echo ""
echo "## remove temparary objects"
echo "#rm $harness_object"
echo "#rm $procedure_source"
echo "#rm $procedure_object"
echo "#rm $test_exec"
echo ""
echo "## leave the test directory"
echo "#popd > /dev/null"
echo "## exit with error code"
echo "exit \$err_code"
echo ""

